_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 75ea5512-ddfd-4769-8dc5-e716a55add91
name: Flipkart
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/359
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
